apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbom-backend
  namespace: sbom

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbom-scanner
  namespace: sbom

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sbom-backend-job-manager
  namespace: sbom
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sbom-backend-job-manager-binding
  namespace: sbom
subjects:
  - kind: ServiceAccount
    name: sbom-backend
    namespace: sbom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbom-backend-job-manager
